### ISSUE TITLE
Add function to run script

### ISSUE THREAD

**Issue by tsarbel** [dekolos/sulfide#13]
Run a script. Can be bash / python etc

Example:

runScript("mkdir testdir")

**Comment by rotous** [comment]
This doesn't seem to be something for Sulfide. Spawning a child process in nodejs is just a one-liner: https://nodejs.org/docs/latest/api/child_process.html#child_process_child_process_execfilesync_file_args_options

So I suggest a "won't fix" for this one.

**Comment by tsarbel** [comment]
Close as won't fix.
